import type { Trail } from "@/lib/types";

export const retirement: Trail = {
  slug: "retirement",
  domain: "F",
  title: "Retirement Savings & Income",
  weight: 18,
  tagline: "The heaviest domain on the exam: plan rules, distributions, and income engineering.",
  status: "live",
  modules: [
    {
      id: "ret-1",
      title: "Qualified Plan Rules",
      blurb: "Coverage testing, vesting, top-heavy rules, NUA — where employer-plan questions get technical.",
      flashcards: [
        { id: "rf1", front: "Ratio percentage coverage test", back: "Plan must cover NHCEs at a rate ≥ 70% of the HCE coverage rate. One of the §410(b) minimum coverage tests." },
        { id: "rf2", front: "Vesting schedules (DC plans)", back: "Employer contributions: 3-year cliff OR 2-to-6-year graded (20%/yr starting year 2). Employee deferrals are always 100% vested immediately." },
        { id: "rf3", front: "Top-heavy plan", back: "Key employees hold > 60% of plan assets/accrued benefits. Triggers minimum contributions for non-key employees and (historically) faster vesting." },
        { id: "rf4", front: "NUA (net unrealized appreciation)", back: "Lump-sum distribution of employer stock: cost basis taxed as ordinary income now; NUA taxed at LTCG rates when sold — regardless of holding period." },
        { id: "rf5", front: "ERISA §404(c)", back: "Fiduciaries get relief from participant investment decisions if the plan offers diversified choices, adequate information, and control — relief from participant choices, not from selecting/monitoring the menu." },
      ],
      questions: [
        {
          id: "rq1", kind: "mc", topic: "F.2", difficulty: 2,
          stem: "A 401(k) plan covers 80% of highly compensated employees and 52% of non-highly compensated employees. Under the ratio percentage test, the plan:",
          choices: [
            "Passes — more than half of NHCEs are covered",
            "Fails — 52% ÷ 80% = 65%, below the required 70%",
            "Passes — only the average benefits test applies to 401(k) plans",
            "Fails — all NHCEs must be covered",
          ],
          answer: 1,
          explanation: "The NHCE coverage ratio must be at least 70% of the HCE ratio. 52/80 = 65% fails; the plan would need the average benefits test to survive.",
        },
        {
          id: "rq2", kind: "mc", topic: "F.3", difficulty: 2,
          stem: "A 58-year-old dentist earning $600,000 with three young employees wants to maximize her own deductible retirement contributions in the next 7 years. Which plan generally allows the LARGEST annual contribution on her behalf?",
          choices: [
            "Safe harbor 401(k) with profit sharing",
            "SEP IRA",
            "Traditional defined benefit plan",
            "SIMPLE IRA",
          ],
          answer: 2,
          explanation: "A DB plan funds a promised benefit, so contributions for an older, highly paid owner with a short horizon can far exceed DC limits — the classic 'older owner, young staff' fact pattern.",
        },
        {
          id: "rq3", kind: "mc", topic: "F.2", difficulty: 1,
          stem: "A safe harbor 401(k) design is chosen primarily to:",
          choices: [
            "Eliminate the employer's fiduciary liability",
            "Automatically satisfy ADP/ACP nondiscrimination testing",
            "Permit contributions above the annual additions limit",
            "Exempt the plan from ERISA",
          ],
          answer: 1,
          explanation: "Safe harbor contributions (e.g., 3% nonelective or a qualifying match, immediately vested) buy out ADP/ACP testing so HCEs can defer the maximum.",
        },
        {
          id: "rq4", kind: "mc", topic: "F.2", difficulty: 1,
          stem: "An employee leaves after exactly 4 years of service. Her plan uses the slowest permitted graded vesting schedule for employer contributions. She is vested in:",
          choices: ["0%", "40%", "60%", "100%"],
          answer: 2,
          explanation: "The 2–6 graded schedule vests 20% per year starting at year 2: year 4 = 60%. (Her own deferrals are always 100% vested.)",
        },
        {
          id: "rq5", kind: "mc", topic: "F.2", difficulty: 2,
          stem: "A plan is top-heavy when:",
          choices: [
            "More than 50% of participants are highly compensated",
            "Key employees hold more than 60% of total plan assets or accrued benefits",
            "The owner's contribution exceeds 25% of total contributions",
            "HCE deferral rates exceed NHCE rates by more than 2%",
          ],
          answer: 1,
          explanation: "Top-heavy = key employees (owners/officers meeting thresholds) hold > 60% of benefits, triggering minimum contributions for non-key employees.",
        },
        {
          id: "rq6", kind: "mc", topic: "F.5", difficulty: 2,
          stem: "An executive retires holding employer stock in her 401(k): plan cost basis $80,000, current value $480,000. She takes a qualifying lump-sum distribution of the stock to a taxable account. Which is correct?",
          choices: [
            "$480,000 is ordinary income now",
            "$80,000 is ordinary income now; $400,000 of NUA is taxed at long-term capital gain rates when sold",
            "Nothing is taxed until the stock is sold, then all at LTCG rates",
            "She must roll the stock to an IRA to get capital gain treatment",
          ],
          answer: 1,
          explanation: "NUA treatment: ordinary income on plan cost basis at distribution; the appreciation inside the plan is LTCG whenever sold. Rolling to an IRA destroys NUA — everything becomes future ordinary income.",
        },
        {
          id: "rq7", kind: "mc", topic: "F.2", difficulty: 2,
          stem: "ERISA §404(c) compliance protects plan fiduciaries from liability for:",
          choices: [
            "Imprudently selected investment menu options",
            "Losses resulting from participants' own investment elections",
            "Failure to remit deferrals timely",
            "All investment losses in the plan",
          ],
          answer: 1,
          explanation: "404(c) shields fiduciaries from participants' allocation choices — never from the duty to prudently select and monitor the menu itself.",
        },
        {
          id: "rq8", kind: "mc", topic: "F.1", difficulty: 1,
          stem: "Which contribution source is ALWAYS 100% immediately vested?",
          choices: [
            "Employer profit-sharing contributions",
            "Employer matching contributions",
            "Employee elective deferrals",
            "Forfeiture reallocations",
          ],
          answer: 2,
          explanation: "A participant's own salary deferrals (and safe harbor employer contributions, and all IRA/SEP/SIMPLE money) are always fully vested; discretionary employer money may vest on a schedule.",
        },
      ],
    },
    {
      id: "ret-2",
      title: "IRAs, Roth & Distributions",
      blurb: "Pro-rata math, the two 5-year clocks, RMDs, inherited IRAs, and penalty exceptions.",
      flashcards: [
        { id: "rf6", front: "Backdoor Roth pro-rata rule", back: "Conversions are taxed proportionally across ALL traditional/SEP/SIMPLE IRA balances (Form 8606). You cannot isolate the nondeductible basis if pre-tax IRA money exists on Dec 31." },
        { id: "rf7", front: "Roth's two 5-year clocks", back: "Clock 1 (earnings): qualified tax-free earnings need 5 years from first Roth contribution AND a trigger (59½, death, disability, first home). Clock 2 (conversions): each conversion has its own 5-year clock for the 10% penalty if under 59½." },
        { id: "rf8", front: "RMD beginning ages (SECURE 2.0)", back: "Age 73 for those born 1951–1959; age 75 for those born 1960 or later. Roth IRAs (and now Roth employer accounts) have no lifetime RMDs for the owner." },
        { id: "rf9", front: "Inherited IRA: 10-year rule", back: "Most non-spouse beneficiaries must empty the account by year 10. Eligible designated beneficiaries (spouse, minor child of owner, disabled, chronically ill, beneficiary <10 yrs younger) may still stretch." },
        { id: "rf10", front: "Rule of 55 vs 59½", back: "Separation from service at 55+ allows penalty-free withdrawals from THAT employer's plan only. IRAs have no rule of 55 — rolling over forfeits it." },
      ],
      questions: [
        {
          id: "rq9", kind: "mc", topic: "F.6", difficulty: 2,
          stem: "A client has $93,000 of pre-tax money in a rollover IRA and makes a $7,000 nondeductible contribution, then converts $7,000 to Roth the next day. The taxable portion of the conversion is approximately:",
          choices: ["$0", "$6,510", "$7,000", "$651"],
          answer: 1,
          explanation: "Pro-rata: basis is $7,000 of a $100,000 aggregate, so only 7% of any conversion is tax-free. $7,000 × 93% = $6,510 taxable. The 'backdoor' only works cleanly with no other pre-tax IRA balances.",
        },
        {
          id: "rq10", kind: "mc", topic: "F.6", difficulty: 2,
          stem: "Maria, 61, opened her first Roth IRA 3 years ago and withdraws all contributions plus earnings today. Which statement is correct?",
          choices: [
            "The entire withdrawal is tax-free and penalty-free — she is over 59½",
            "Contributions come out tax-free; earnings are taxable (but penalty-free) because the 5-year clock isn't met",
            "Everything is taxable plus a 10% penalty",
            "Earnings are tax-free but contributions are taxable",
          ],
          answer: 1,
          explanation: "Being 59½ kills the penalty, but tax-free earnings also require the 5-year clock from the first contribution. Contributions always return tax-free first under the ordering rules; the earnings are taxable here.",
        },
        {
          id: "rq11", kind: "mc", topic: "F.5", difficulty: 1,
          stem: "Under SECURE 2.0, a client born in 1962 must begin lifetime RMDs from her traditional IRA at age:",
          choices: ["70½", "72", "73", "75"],
          answer: 3,
          explanation: "Born 1960 or later → RMDs begin at 75. Born 1951–1959 → 73. Roth IRAs have no lifetime RMDs for the owner.",
        },
        {
          id: "rq12", kind: "mc", topic: "F.5", difficulty: 2,
          stem: "A 45-year-old daughter inherits her father's traditional IRA in 2026 (he died after his required beginning date). She must:",
          choices: [
            "Take only a lump sum within 5 years",
            "Empty the account by the end of year 10, taking annual RMDs in years 1–9 based on her life expectancy",
            "Stretch RMDs over her single life expectancy with no 10-year limit",
            "Roll it into her own IRA",
          ],
          answer: 1,
          explanation: "She's a non-eligible designated beneficiary → 10-year rule. Because the owner died after RMDs began, annual distributions are also required in years 1–9 ('at least as rapidly' rule). Only spouses may treat an inherited IRA as their own.",
        },
        {
          id: "rq13", kind: "mc", topic: "F.5", difficulty: 2,
          stem: "Which beneficiary may still 'stretch' inherited IRA distributions over life expectancy?",
          choices: [
            "The owner's 50-year-old son",
            "The owner's healthy 30-year-old grandchild",
            "The owner's sibling who is 4 years younger",
            "A charity",
          ],
          answer: 2,
          explanation: "Eligible designated beneficiaries include individuals not more than 10 years younger than the owner. Adult children and grandchildren get the 10-year rule; charities (non-designated) face even shorter timelines.",
        },
        {
          id: "rq14", kind: "mc", topic: "F.4", difficulty: 2,
          stem: "A 52-year-old wants penalty-free income from her IRA via substantially equal periodic payments (72(t)/SEPP). Which is TRUE?",
          choices: [
            "Payments may stop once she finds a job",
            "Payments must continue for the LONGER of 5 years or until age 59½, or all prior penalty relief is recaptured",
            "Payments must continue exactly 5 years",
            "SEPP is available only from employer plans",
          ],
          answer: 1,
          explanation: "Modifying a SEPP before the later of 5 years or 59½ retroactively triggers the 10% penalty plus interest on every prior payment. At 52, she's committed until 59½.",
        },
        {
          id: "rq15", kind: "mc", topic: "F.4", difficulty: 2,
          stem: "A 56-year-old is laid off and needs money from her 401(k) at that employer. To preserve penalty-free access she should:",
          choices: [
            "Roll the 401(k) to an IRA, then withdraw",
            "Withdraw directly from the 401(k) — separation from service at 55+ avoids the 10% penalty",
            "Take a 72(t) from the 401(k)",
            "Wait until 59½ regardless",
          ],
          answer: 1,
          explanation: "The rule of 55 applies to the plan of the employer you separated from at 55+. Rolling to an IRA forfeits it — IRAs have no age-55 exception. A classic costly rollover mistake.",
        },
        {
          id: "rq16", kind: "mc", topic: "F.6", difficulty: 1,
          stem: "A stay-at-home spouse with no earned income may contribute to an IRA if:",
          choices: [
            "She has investment income above the contribution amount",
            "The couple files jointly and the working spouse has sufficient compensation",
            "Never — IRA contributions require personal earned income",
            "Only to a Roth, not a traditional IRA",
          ],
          answer: 1,
          explanation: "Spousal IRA: a non-working spouse may fund a traditional or Roth IRA based on the working spouse's compensation, if filing jointly.",
        },
      ],
    },
    {
      id: "ret-3",
      title: "Social Security & Retirement Income",
      blurb: "A claiming-strategy case plus the income-engineering toolkit: taxation, sequence risk, annuity math.",
      flashcards: [
        { id: "rf11", front: "Claiming early vs delaying", back: "Claiming at 62 with FRA 67 cuts the benefit ~30%. Delaying past FRA earns 8%/year in delayed credits to age 70 (no credits after 70)." },
        { id: "rf12", front: "Survivor benefit planning", back: "At first death, the survivor keeps the LARGER of the two benefits. Delaying the higher earner's claim is effectively joint-life longevity insurance." },
        { id: "rf13", front: "Provisional income", back: "AGI + tax-exempt interest + ½ of Social Security. Crossing the thresholds makes up to 50%, then up to 85%, of benefits taxable." },
        { id: "rf14", front: "Sequence of returns risk", back: "Poor returns early in the withdrawal phase do disproportionate damage because withdrawals lock in losses. Order of returns matters once distributions begin — not during pure accumulation." },
        { id: "rf15", front: "Annuity exclusion ratio", back: "Investment in contract ÷ expected total return = % of each payment that is tax-free return of basis (until basis is fully recovered)." },
      ],
      questions: [
        {
          id: "rq17", kind: "scenario", topic: "F.8", difficulty: 2,
          caseText: "Tom (66, FRA 67, PIA $3,400) and Linda (62, FRA 67, PIA $1,400) are retiring now. Tom's family history suggests strong longevity; Linda's does not. They have ample portfolio assets to bridge several years of expenses.",
          stem: "If Linda claims her own benefit now at 62, her monthly check will be approximately:",
          choices: ["$1,400", "$1,120", "$980", "$700"],
          answer: 2,
          explanation: "Claiming 60 months early: reduction is 5/9 of 1% × 36 months (20%) + 5/12 of 1% × 24 months (10%) = 30%. $1,400 × 70% = $980.",
        },
        {
          id: "rq18", kind: "scenario", topic: "F.8", difficulty: 2,
          caseText: "Tom (66, FRA 67, PIA $3,400) and Linda (62, FRA 67, PIA $1,400) are retiring now. Tom's family history suggests strong longevity; Linda's does not. They have ample portfolio assets to bridge several years of expenses.",
          stem: "The strongest argument for Tom delaying his claim to age 70 is:",
          choices: [
            "His benefit grows 8% per year past FRA, and as the larger benefit it becomes Linda's survivor benefit — insuring whichever of them lives longest",
            "Delayed credits continue accruing until age 72",
            "Linda's spousal benefit will also grow 8% per year while he waits",
            "It reduces the taxable portion of Linda's benefit",
          ],
          answer: 0,
          explanation: "Delayed credits stop at 70, and spousal benefits do NOT share in delayed credits — but survivor benefits DO. Maximizing the higher earner's benefit protects the survivor, whoever it is. Their portfolio can bridge the gap.",
        },
        {
          id: "rq19", kind: "scenario", topic: "F.8", difficulty: 2,
          caseText: "Tom (66, FRA 67, PIA $3,400) and Linda (62, FRA 67, PIA $1,400) are retiring now. Tom's family history suggests strong longevity; Linda's does not. They have ample portfolio assets to bridge several years of expenses.",
          stem: "Linda instead takes a part-time job paying well above the annual earnings limit while collecting at 62. Before her FRA, her benefits will be:",
          choices: [
            "Unaffected — the earnings test was repealed",
            "Reduced $1 for every $2 earned above the limit, with withheld amounts recrediting her benefit at FRA",
            "Permanently forfeited $1 for every $2 above the limit",
            "Reduced $1 for every $3 above the limit",
          ],
          answer: 1,
          explanation: "Before FRA: $1 withheld per $2 over the limit ($1-per-$3 applies only in the FRA year). Withheld benefits aren't lost — the reduction is actuarially recomputed at FRA. After FRA there is no earnings test.",
        },
        {
          id: "rq20", kind: "mc", topic: "F.8", difficulty: 1,
          stem: "Provisional income for determining Social Security taxation equals:",
          choices: [
            "AGI only",
            "AGI + tax-exempt interest + 50% of Social Security benefits",
            "Taxable income + 85% of benefits",
            "AGI + 100% of benefits",
          ],
          answer: 1,
          explanation: "Municipal bond interest counts in provisional income — a frequent surprise. Crossing the thresholds exposes up to 50%, then up to 85%, of benefits to tax.",
        },
        {
          id: "rq21", kind: "mc", topic: "F.7", difficulty: 2,
          stem: "Two retirees earn identical average returns over 25 years, but one experiences losses in the first three years of withdrawals and the other in the last three. The early-loss retiree runs out of money. This illustrates:",
          choices: [
            "Inflation risk",
            "Sequence of returns risk",
            "Reinvestment rate risk",
            "Longevity risk",
          ],
          answer: 1,
          explanation: "With ongoing withdrawals, early losses are sold into and never recovered. Mitigants: cash/bond buffers, flexible (guardrail) spending, lower early equity glide paths, or annuitized income floors.",
        },
        {
          id: "rq22", kind: "mc", topic: "F.7", difficulty: 2,
          stem: "A client pays $120,000 for an immediate annuity expected to pay $800/month over a 25-year expected return period ($240,000 total). The tax-free portion of each payment is:",
          choices: ["$800", "$400", "$0 until basis is recovered", "$266"],
          answer: 1,
          explanation: "Exclusion ratio = $120,000 ÷ $240,000 = 50%, so $400 of each payment is tax-free return of basis until the full $120,000 is recovered, after which payments are fully taxable.",
        },
        {
          id: "rq23", kind: "mc", topic: "F.7", difficulty: 1,
          stem: "The '4% rule' guideline is BEST described as:",
          choices: [
            "Withdraw 4% of the current balance every year",
            "An initial withdrawal of ~4% of the starting portfolio, then adjusted annually for inflation, historically surviving ~30 years",
            "A guaranteed safe withdrawal rate",
            "A rule requiring 4% cash reserves",
          ],
          answer: 1,
          explanation: "It's an inflation-adjusted initial-withdrawal heuristic from historical U.S. data, not a guarantee — assumptions about horizon, allocation, and market history all matter, which is exactly what the exam probes.",
        },
      ],
    },
  ],
};
