import type { Trail } from "@/lib/types";

export const taxPlanning: Trail = {
  slug: "tax-planning",
  domain: "E",
  title: "Tax Planning",
  weight: 14,
  tagline: "Basis, entities, AMT, and the strategies that separate passing from failing.",
  status: "live",
  modules: [
    {
      id: "tax-1",
      title: "Income Tax Fundamentals",
      blurb: "Basis rules, exclusions, doctrines, and the traps inside 'easy' topics.",
      flashcards: [
        { id: "tf1", front: "Dual basis rule for gifts", back: "If FMV at gift < donor's basis: use donor's basis for gains, FMV at gift for losses. A sale between the two produces NO gain or loss." },
        { id: "tf2", front: "§121 home sale exclusion", back: "$250k single / $500k MFJ. Must own AND use as principal residence 2 of last 5 years. Partial exclusion allowed for job change, health, or unforeseen circumstances — prorated." },
        { id: "tf3", front: "Net Investment Income Tax", back: "3.8% on the LESSER of net investment income or MAGI over the threshold ($200k single / $250k MFJ, not indexed)." },
        { id: "tf4", front: "Kiddie tax", back: "Unearned income of a child under 19 (or under 24 if full-time student not providing >half own support) above the threshold is taxed at the PARENTS' marginal rate." },
        { id: "tf5", front: "Constructive receipt", back: "Income is taxable when made available without substantial restriction — even if not actually collected. A check received Dec 31 is that year's income." },
      ],
      questions: [
        {
          id: "tq1", kind: "mc", topic: "E.2", difficulty: 2,
          stem: "Dana receives stock as a gift. The donor's basis was $40,000; FMV on the date of the gift was $28,000. Dana later sells the stock for $33,000. What is Dana's recognized gain or loss?",
          choices: ["$7,000 loss", "$5,000 gain", "$0 — no gain or loss", "$12,000 loss"],
          answer: 2,
          explanation: "Dual basis rule: gain basis is $40,000 (no gain at $33,000), loss basis is $28,000 (no loss at $33,000). Selling between the two bases produces no recognized gain or loss.",
        },
        {
          id: "tq2", kind: "mc", topic: "E.2", difficulty: 1,
          stem: "Which transfer results in the recipient taking a fully stepped-up basis equal to fair market value?",
          choices: [
            "Stock gifted two days before the donor's death",
            "Stock inherited from a decedent's estate",
            "Stock transferred to an ex-spouse under a divorce decree",
            "Stock received as compensation and immediately vested",
          ],
          answer: 1,
          explanation: "Inherited property takes FMV basis at death (or alternate valuation date). Gifts carry over basis; §1041 divorce transfers carry over basis; compensatory stock takes basis equal to the income recognized — which equals FMV, but the question's cleanest 'step-up' answer is inheritance, the rule being tested.",
        },
        {
          id: "tq3", kind: "mc", topic: "E.1", difficulty: 1,
          stem: "A self-employed consultant completes a project on December 20 and could have collected payment that day, but asks the client to mail the check in January to defer the income. Under the constructive receipt doctrine, the payment is:",
          choices: [
            "Taxable in January, when actually received",
            "Taxable in December, because it was available without restriction",
            "Taxable half in each year",
            "Not taxable until deposited",
          ],
          answer: 1,
          explanation: "Cash-basis taxpayers cannot defer income that was made available without substantial limitation. Asking the payer to delay does not defeat constructive receipt.",
        },
        {
          id: "tq4", kind: "mc", topic: "E.2", difficulty: 2,
          stem: "A married couple sells their principal residence after owning and living in it for only 14 months. The sale was triggered by a job relocation 600 miles away. Their realized gain is $310,000. Assuming a $500,000 MFJ exclusion limit, how much gain is excluded under §121?",
          choices: ["$0 — the two-year test fails", "$310,000 — full exclusion", "$291,667", "$250,000"],
          answer: 2,
          explanation: "A qualifying job change allows a PARTIAL exclusion: (14 ÷ 24) × $500,000 = $291,667 of maximum exclusion — the limit is prorated, not the gain. Since $291,667 < $310,000 gain, $291,667 is excluded.",
        },
        {
          id: "tq5", kind: "mc", topic: "E.3", difficulty: 2,
          stem: "A single filer has MAGI of $230,000, including $45,000 of net investment income. Assume the NIIT threshold for single filers is $200,000. The net investment income tax owed is:",
          choices: ["$1,710", "$1,140", "$8,740", "$0"],
          answer: 1,
          explanation: "NIIT = 3.8% × lesser of NII ($45,000) or MAGI excess ($230,000 − $200,000 = $30,000). 3.8% × $30,000 = $1,140.",
        },
        {
          id: "tq6", kind: "mc", topic: "E.1", difficulty: 1,
          stem: "A 20-year-old full-time college student receives $9,000 of dividend income and has no earned income. Her parents provide most of her support. Her dividend income above the kiddie-tax threshold is taxed at:",
          choices: ["Her own marginal rate", "The trust and estate rate schedule", "Her parents' marginal rate", "A flat 10%"],
          answer: 2,
          explanation: "The kiddie tax applies to full-time students under 24 who don't provide more than half their own support; excess unearned income is taxed at the parents' marginal rate (post-2019 rules restored the parental-rate method).",
        },
        {
          id: "tq7", kind: "mc", topic: "E.4", difficulty: 2,
          stem: "An activity generates losses in 4 of its first 6 years. Which statement about §183 (hobby loss) is MOST accurate?",
          choices: [
            "The activity is automatically a hobby; losses are permanently disallowed",
            "Profit in 3 of 5 consecutive years creates a presumption the activity is for profit, shifting the burden to the IRS",
            "Hobby income is excluded from gross income, so the losses are irrelevant",
            "Losses are deductible as long as the taxpayer materially participates",
          ],
          answer: 1,
          explanation: "The 3-of-5-year profit test (2-of-7 for horses) creates a rebuttable presumption of profit motive. Failing it doesn't automatically make the activity a hobby — but hobby losses are nondeductible while hobby income remains taxable.",
        },
        {
          id: "tq8", kind: "mc", topic: "E.2", difficulty: 1,
          stem: "Which item is deductible ABOVE the line (in arriving at AGI)?",
          choices: [
            "State income taxes paid",
            "Charitable contributions",
            "One-half of self-employment tax",
            "Mortgage interest on a primary residence",
          ],
          answer: 2,
          explanation: "Half of SE tax is an adjustment to income. The others are itemized deductions — a distinction that drives MAGI-based phaseouts everywhere else in planning.",
        },
      ],
    },
    {
      id: "tax-2",
      title: "Entities & Property Transactions",
      blurb: "S corp basis, recapture, installment sales, wash sales — the calculation engine of Domain E.",
      flashcards: [
        { id: "tf6", front: "S corp loss limitation", back: "Losses deductible only to the extent of stock basis + direct loan basis. Bank loans merely guaranteed by the shareholder do NOT create basis (unlike partnerships)." },
        { id: "tf7", front: "§1245 recapture", back: "Gain on depreciated personal property is ordinary income to the extent of ALL depreciation taken; any excess is §1231 gain." },
        { id: "tf8", front: "Wash sale rule", back: "Loss disallowed if substantially identical security bought within 30 days before OR after the sale. Disallowed loss is ADDED to the basis of the replacement shares." },
        { id: "tf9", front: "Installment sale gross profit %", back: "Gross profit ÷ contract price. Each principal payment × GP% = taxable gain that year. Depreciation recapture is recognized in full in year of sale." },
        { id: "tf10", front: "QBI deduction (§199A)", back: "Generally 20% of qualified business income. Above the income thresholds, SSTBs phase out entirely and non-SSTBs face W-2 wage / UBIA limits." },
      ],
      questions: [
        {
          id: "tq9", kind: "mc", topic: "E.5", difficulty: 2,
          stem: "An S corporation shareholder has $15,000 stock basis and personally guaranteed a $50,000 bank loan to the corporation. Her share of this year's loss is $40,000. How much loss may she deduct currently?",
          choices: ["$40,000", "$15,000", "$55,000", "$0"],
          answer: 1,
          explanation: "S corp shareholders get basis only for direct loans to the corporation — a guarantee creates no basis. Deduction is limited to $15,000 stock basis; $25,000 carries forward.",
        },
        {
          id: "tq10", kind: "mc", topic: "E.6", difficulty: 2,
          stem: "Equipment purchased for $100,000 with $60,000 of depreciation taken is sold for $115,000. How is the gain characterized?",
          choices: [
            "$75,000 §1231 gain",
            "$60,000 ordinary income; $15,000 §1231 gain",
            "$75,000 ordinary income",
            "$15,000 ordinary income; $60,000 §1231 gain",
          ],
          answer: 1,
          explanation: "Adjusted basis = $40,000; gain = $75,000. §1245 recaptures all $60,000 of depreciation as ordinary income; the $15,000 above original cost is §1231 gain.",
        },
        {
          id: "tq11", kind: "mc", topic: "E.6", difficulty: 2,
          stem: "In a §1031 exchange, a taxpayer trades real property (basis $200,000, FMV $500,000) for replacement real property worth $440,000 plus $60,000 cash. Recognized gain is:",
          choices: ["$300,000", "$60,000", "$0", "$240,000"],
          answer: 1,
          explanation: "Realized gain is $300,000, but recognition is limited to boot received: $60,000 cash. The rest defers into the replacement property's basis.",
        },
        {
          id: "tq12", kind: "mc", topic: "E.5", difficulty: 1,
          stem: "A primary tax reason an owner-operator elects S corporation status over a single-member LLC (default taxation) is:",
          choices: [
            "S corp profits are exempt from federal income tax",
            "Distributions above a reasonable salary avoid self-employment/payroll tax",
            "S corps may have unlimited foreign shareholders",
            "S corp losses are never limited by basis",
          ],
          answer: 1,
          explanation: "Only reasonable compensation is subject to payroll tax; remaining pass-through profit avoids SE tax. The IRS polices 'reasonable salary' for exactly this reason.",
        },
        {
          id: "tq13", kind: "mc", topic: "E.6", difficulty: 2,
          stem: "Land with a basis of $120,000 is sold for $300,000: $60,000 down this year and a note for the balance. Under the installment method, how much gain is recognized in year one?",
          choices: ["$36,000", "$60,000", "$24,000", "$180,000"],
          answer: 0,
          explanation: "Gross profit % = $180,000 ÷ $300,000 = 60%. Year-one payment $60,000 × 60% = $36,000 of gain.",
        },
        {
          id: "tq14", kind: "mc", topic: "E.7", difficulty: 2,
          stem: "An investor sells 100 shares at a $4,000 loss on March 10, then buys 100 identical shares on March 25 for $20,000. Which is correct?",
          choices: [
            "The $4,000 loss is deductible; new basis is $20,000",
            "The loss is disallowed; new basis is $24,000",
            "The loss is disallowed; new basis is $16,000",
            "The loss is deductible only against capital gains; new basis is $20,000",
          ],
          answer: 1,
          explanation: "Wash sale: repurchase within 30 days disallows the loss, and the disallowed $4,000 is added to the replacement basis ($20,000 + $4,000 = $24,000), preserving it for the future. The holding period also tacks.",
        },
        {
          id: "tq15", kind: "mc", topic: "E.5", difficulty: 2,
          stem: "A married CPA (an SSTB owner) has taxable income well above the §199A phaseout range. Her QBI deduction is:",
          choices: [
            "20% of QBI, no limits",
            "Limited by the W-2 wage test only",
            "Zero — SSTB income is fully phased out above the threshold",
            "20% of taxable income",
          ],
          answer: 2,
          explanation: "Specified service trades or businesses (health, law, accounting, financial services, etc.) lose the QBI deduction entirely once taxable income exceeds the top of the phaseout range.",
        },
        {
          id: "tq16", kind: "mc", topic: "E.2", difficulty: 1,
          stem: "Net capital losses for an individual in excess of capital gains may offset ordinary income up to ____ per year, with the remainder:",
          choices: [
            "$3,000; carried forward indefinitely",
            "$3,000; carried back three years",
            "$10,000; carried forward five years",
            "$0; capital losses only offset capital gains",
          ],
          answer: 0,
          explanation: "Individuals: $3,000 of net capital loss against ordinary income annually ($1,500 MFS); unused losses carry forward indefinitely, retaining their character.",
        },
      ],
    },
    {
      id: "tax-3",
      title: "Strategies, AMT & Charitable",
      blurb: "A case study plus the planning levers: AMT triggers, safe harbors, and charitable structuring.",
      flashcards: [
        { id: "tf11", front: "Charitable AGI limits (cash vs appreciated)", back: "Public charity: cash up to 60% of AGI; long-term appreciated property up to 30% of AGI at FMV. 5-year carryforward for excess." },
        { id: "tf12", front: "Qualified Charitable Distribution", back: "IRA owners 70½+ may transfer directly to charity (annual limit, indexed). Excluded from income, counts toward RMD, no charitable deduction. Not available from active employer plans." },
        { id: "tf13", front: "Estimated tax safe harbor", back: "No underpayment penalty if you pay the lesser of 90% of current-year tax or 100% of prior-year tax (110% if prior-year AGI exceeded $150,000)." },
        { id: "tf14", front: "Classic AMT triggers", back: "ISO bargain element at exercise (if held), large state tax deductions, private activity bond interest, accelerated depreciation adjustments." },
        { id: "tf15", front: "Capital gain rates (LTCG)", back: "0% / 15% / 20% by income bracket; collectibles capped at 28%; unrecaptured §1250 gain capped at 25%; NIIT may stack 3.8% on top." },
      ],
      questions: [
        {
          id: "tq17", kind: "scenario", topic: "E.8", difficulty: 2,
          caseText: "Marcus, 58, has AGI of $400,000 and holds stock purchased 6 years ago for $50,000, now worth $200,000. He gives roughly $20,000/year to his church and is charitably inclined but expects lower income after retiring at 62. He takes the standard deduction in most years.",
          stem: "Marcus donates the stock directly to his church (a public charity). Which is correct?",
          choices: [
            "He deducts $50,000 and recognizes no gain",
            "He deducts $200,000, limited to 30% of AGI, and recognizes no gain",
            "He deducts $200,000, limited to 60% of AGI, and recognizes $150,000 of gain",
            "He must sell the stock first to claim any deduction",
          ],
          answer: 1,
          explanation: "Long-term appreciated stock to a public charity: FMV deduction, capped at 30% of AGI ($120,000 here; $80,000 carries forward up to 5 years), and the embedded gain permanently escapes tax.",
        },
        {
          id: "tq18", kind: "scenario", topic: "E.8", difficulty: 2,
          caseText: "Marcus, 58, has AGI of $400,000 and holds stock purchased 6 years ago for $50,000, now worth $200,000. He gives roughly $20,000/year to his church and is charitably inclined but expects lower income after retiring at 62. He takes the standard deduction in most years.",
          stem: "Marcus's advisor suggests contributing the stock to a donor-advised fund this year instead of giving $20,000 annually. The PRIMARY tax logic is:",
          choices: [
            "DAF contributions are deductible up to 100% of AGI",
            "Bunching several years of giving into one high-income year beats annual gifts that never exceed his standard deduction",
            "DAFs allow the donor to retain legal control of the assets",
            "DAF grants to charity are deductible a second time when distributed",
          ],
          answer: 1,
          explanation: "Bunching concentrates deductions into the year they clear the standard-deduction hurdle — ideally his highest-bracket working years — while the DAF lets him keep granting $20k/year to the church on his normal schedule.",
        },
        {
          id: "tq19", kind: "scenario", topic: "E.8", difficulty: 2,
          caseText: "Marcus, 58, has AGI of $400,000 and holds stock purchased 6 years ago for $50,000, now worth $200,000. He gives roughly $20,000/year to his church and is charitably inclined but expects lower income after retiring at 62. He takes the standard deduction in most years.",
          stem: "Marcus asks about making qualified charitable distributions (QCDs) from his IRA this year. The correct response is:",
          choices: [
            "Yes — QCDs are allowed at any age",
            "Yes — but only up to 30% of AGI",
            "Not yet — QCDs require the IRA owner to be at least 70½",
            "Not yet — QCDs require the IRA owner to be at least 59½",
          ],
          answer: 2,
          explanation: "QCDs are available only at 70½ or later, made directly from the IRA to charity, excluded from income, and (once RMDs begin) count toward the RMD. At 58, Marcus must wait.",
        },
        {
          id: "tq20", kind: "mc", topic: "E.9", difficulty: 2,
          stem: "An executive exercises incentive stock options (ISOs) and HOLDS the shares past year-end. The bargain element at exercise is:",
          choices: [
            "Ordinary income for regular tax in the exercise year",
            "An AMT preference/adjustment item in the exercise year, but not regular taxable income",
            "Capital gain in the exercise year",
            "Never taxable if the shares are held two years",
          ],
          answer: 1,
          explanation: "Exercise-and-hold defers regular tax but the bargain element is an AMT adjustment — the classic AMT trap. Selling in the same calendar year (a disqualifying disposition) eliminates the AMT issue but converts the element to ordinary income.",
        },
        {
          id: "tq21", kind: "mc", topic: "E.10", difficulty: 1,
          stem: "A taxpayer's prior-year AGI was $300,000 with $70,000 of tax. To avoid an underpayment penalty this year via the prior-year safe harbor, she must pay in at least:",
          choices: ["$63,000", "$70,000", "$77,000", "90% of last year's tax"],
          answer: 2,
          explanation: "Prior-year AGI over $150,000 raises the safe harbor to 110% of prior-year tax: $70,000 × 110% = $77,000 (or 90% of the current year's tax, if lower).",
        },
        {
          id: "tq22", kind: "mc", topic: "E.10", difficulty: 2,
          stem: "A client retiring in March expects unusually low taxable income this year before pensions and Social Security begin next year. The MOST tax-efficient use of this 'gap year' is generally to:",
          choices: [
            "Defer all income to future years",
            "Accelerate deductions into this year",
            "Convert traditional IRA dollars to Roth up to the top of a low bracket",
            "Harvest long-term gains to reset basis, then immediately repurchase — wash sale rules block this",
          ],
          answer: 2,
          explanation: "Low-income years are conversion windows: fill the low brackets with Roth conversions. (Gain harvesting at 0% LTCG can also work — and wash-sale rules do NOT apply to gains — but bracket-filling conversions are the textbook gap-year answer.) Deductions are worth least in low-income years.",
        },
      ],
    },
  ],
};
